### ISSUE TITLE
Erorr when trying to make a backup from a URL

### ISSUE THREAD

**Issue by holema** [Symandy/DatabaseBackupBundle#8]
Hello,

I tried your great package but I get this error

```
$ php bin/console symandy:databases:backup app

                                                                                                                        
 [INFO] The backup app is in progress



In Process.php line 1578:

  Command line is missing a value for parameter "MYSQL_DUMP": "${:MYSQL_DUMP}" -u "${:DB_USER}" -h "${:DB_HOST}" -P "${:DB_PORT}" "${:DB_NAME}" > "${:FILEPATH}"  
                                                                                                                                                                  

symandy:databases:backup [<backups>...]

```

Best regards

**Comment by SVillette** [comment]
Hi,

Thank you for reporting this issue. 
I guess something is missing in your configuration. 

But of course,  the error message in not explicit that all.

I see what I can do to improve this message. 

And in order to resolve your issue, I invite you to check if any connection parameter would be missing 

Check [this file](https://github.com/Symandy/DatabaseBackupBundle/blob/v0.3.0/src/Command/BackupDatabasesCommand.php#L125-L133)  for more information

**Comment by holema** [comment]
Hello I found the issue. The error is thrown when mysqldump is not in the PATH variable.
Propably it would be good the explicit name the missing executable in the error message

I realy love the bundle and it will be installed in all my applications in the future

I will make a fork of it, because one feature is missing atm. It would be great if the database is not only saved to a file but also imported into a backup database. So on the backup database is a miror of the actual prod database.

**Comment by SVillette** [comment]
That's a nice catch, I will fix this issue. It seems that `$mysqldump = (new ExecutableFinder())->find('mysqldump');` is null and as it is never checked after, the generic process error appears.

Thanks you for this words, I appreciate it !

About the missing feature, I don't really understand what you want. Can you open another issue (to move the discussion in a specific place) with some details ?
